# Generated by Django 5.1.1 on 2024-10-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_media/', verbose_name='Изображение')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.education', verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Изображение диплома',
                'verbose_name_plural': 'Изображения дипломов',
            },
        ),
    ]
